import Head from "next/head";

import { MainContainer } from "@/components/MainContainer";
import { Title } from "@/components/Title";
import { TodoList } from "@/components/TodoList";
import { FormSection } from "@/components/FormSection";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className={styles.mainSection}>
          <Title>To do:</Title>
          <TodoList
            items={[
              { text: "Buy milk" },
              { text: "Buy eggs" },
              { text: "Buy bread" },
            ]}
          />
          <FormSection />
        </div>
      </MainContainer>
    </>
  );
}
