import React, { useState } from "react";

import Head from "next/head";

import { MainContainer } from "@/components/MainContainer";
import { Title } from "@/components/Title";
import { TodoList } from "@/components/TodoList";
import { FormSection } from "@/components/FormSection";

import { useData } from "@/hooks/useData";

import styles from "@/styles/Home.module.css";

export default function Home() {
  const { data, addData, removeData, toggleComplete } = useData([
    { id: "00001", task: "Wake up", complete: false },
    { id: "00002", task: "Eat breakfast", complete: false },
    { id: "00003", task: "Go to work", complete: false },
  ]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className={styles.mainSection}>
          <Title>To do:</Title>
          <TodoList
            data={data}
            removeData={removeData}
            toggleComplete={toggleComplete}
          />
          <FormSection addData={addData} />
        </div>
      </MainContainer>
    </>
  );
}
