import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.mainSection}>
          <h1 className={styles.title}>To do:</h1>
          <ul className="todo-list">
            <li className="todo-item">
              <span className="todo-text">s</span>
              <div className="todo-buttons">
                <button className="button-complete">✓</button>
                <button className="button-delete">Ｘ</button>
              </div>
            </li>
          </ul>
          <div className="form-section">
            <hr />
            <div className="form-container">
              <form className="add-task-form">
                <div className="form-group">
                  <label className="task-label">Task</label>
                  <div className="input-container">
                    <input className="task-input" />
                  </div>
                </div>
                <div className="form-group">
                  <div className="input-container">
                    <input className="extra-input" />
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
