import Head from 'next/head';

import { Navbar } from '@/components/organisms/Navbar';

import styles from './IndexTemplate.module.css';

export const IndexTemplate = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={styles.root}>
          <Navbar />
        </div>
        <h1 className='text-3xl font-bold underline'>Hello world!</h1>
      </main>
    </>
  );
};
